# MAKEFILE
# ============================================================
# Project configuration (generated by `make init`)
# ============================================================
-include .project.mk

# ============================================================
# Directories
# ============================================================
BIN_DIR      := $(CURDIR)/bin
PROTO_DIR    := proto
GEN_DIR      := gen

# ============================================================
# Tool versions
# ============================================================
BUF_VERSION                 := 1.32.2
PROTOC_GEN_GO_VERSION       := v1.36.1
PROTOC_GEN_GO_GRPC_VERSION  := v1.5.1
GRPC_GATEWAY_VERSION        := v2.23.0
OPENAPI_VERSION             := v2.19.1
GO_SCAFFOLD_VERSION         := latest

# ============================================================
# Tool binaries
# ============================================================
BUF                 := $(BIN_DIR)/buf
PROTOC_GEN_GO       := $(BIN_DIR)/protoc-gen-go
PROTOC_GEN_GO_GRPC  := $(BIN_DIR)/protoc-gen-go-grpc
PROTOC_GEN_GW       := $(BIN_DIR)/protoc-gen-grpc-gateway
PROTOC_GEN_OPENAPI  := $(BIN_DIR)/protoc-gen-openapiv2
GO_SCAFFOLD         := $(BIN_DIR)/go-scaffold

# ============================================================
# Defaults
# ============================================================
.DEFAULT_GOAL := help
.SILENT:

BUF_CMD = PATH=$(BIN_DIR):$$PATH $(BUF)

# ============================================================
# Help
# ============================================================
help:
	echo ""
	echo "Available targets:"
	echo ""
	echo "  make init PROJECT_NAME=... MODULE=...  Initialize project"
	echo "  make tools                               Install all tools into ./bin"
	echo "  make scaffold-tools                       Install go-scaffold optionally"
	echo "  make generate                             Generate proto + scaffold"
	echo "  make lint                                 Proto lint (buf)"
	echo "  make run                                  Run service"
	echo "  make tidy                                 go mod tidy"
	echo "  make clean                                Remove generated artifacts"
	echo ""

# ============================================================
# Init (one-time)
# ============================================================
init:
	if [ -f .project.mk ]; then \
		echo ".project.mk already exists. Remove it to re-init."; \
		exit 1; \
	fi
	if [ -z "$(PROJECT_NAME)" ] || [ -z "$(MODULE)" ]; then \
		echo "Usage:"; \
		echo "  make init PROJECT_NAME=your-service MODULE=github.com/you/your-service"; \
		exit 1; \
	fi
	# создаем buf.gen.yaml если не существует
	@if [ ! -f buf.gen.yaml ]; then \
		echo "version: v1" > buf.gen.yaml; \
		echo "plugins:" >> buf.gen.yaml; \
		echo "  - name: go" >> buf.gen.yaml; \
		echo "    out: gen/go" >> buf.gen.yaml; \
		echo "    opt: paths=source_relative" >> buf.gen.yaml; \
		echo "  - name: go-grpc" >> buf.gen.yaml; \
		echo "    out: gen/go" >> buf.gen.yaml; \
		echo "    opt: paths=source_relative" >> buf.gen.yaml; \
		echo "  - name: grpc-gateway" >> buf.gen.yaml; \
		echo "    out: gen/go" >> buf.gen.yaml; \
		echo "    opt: paths=source_relative" >> buf.gen.yaml; \
		echo "  - name: openapiv2" >> buf.gen.yaml; \
		echo "    out: gen/openapi" >> buf.gen.yaml; \
		echo "    opt: paths=source_relative" >> buf.gen.yaml; \
		echo "Created buf.gen.yaml"; \
	fi	
	echo "PROJECT_NAME := $(PROJECT_NAME)" > .project.mk
	echo "MODULE       := $(MODULE)" >> .project.mk
	echo "Project initialized:"
	echo "  PROJECT_NAME = $(PROJECT_NAME)"
	echo "  MODULE       = $(MODULE)"
	mkdir -p cmd/go-base internal internal/handler internal/service proto/$(PROJECT_NAME) gen
	# Создаем go.mod
	go mod init $(MODULE)
	$(MAKE) tools tidy

# ============================================================
# Tools
# ============================================================
tools: $(BIN_DIR) buf protoc-plugins

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

buf:
	curl -sSL \
	  https://github.com/bufbuild/buf/releases/download/v$(BUF_VERSION)/buf-Linux-x86_64 \
	  -o $(BUF)
	chmod +x $(BUF)

protoc-plugins:
	GOBIN=$(BIN_DIR) go install google.golang.org/protobuf/cmd/protoc-gen-go@$(PROTOC_GEN_GO_VERSION)
	GOBIN=$(BIN_DIR) go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@$(PROTOC_GEN_GO_GRPC_VERSION)
	GOBIN=$(BIN_DIR) go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@$(GRPC_GATEWAY_VERSION)
	GOBIN=$(BIN_DIR) go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@$(OPENAPI_VERSION)

# Optional: go-scaffold installation
scaffold-tools:
	if [ -z "$(GO_SCAFFOLD_MODULE)" ]; then \
		echo "GO_SCAFFOLD_MODULE not set, skipping go-scaffold install"; \
		exit 0; \
	fi
	GOBIN=$(BIN_DIR) go install $(GO_SCAFFOLD_MODULE)@$(GO_SCAFFOLD_VERSION)

# ============================================================
# Generate
# ============================================================
generate: proto-generate scaffold

proto-generate:
	$(BUF_CMD) generate $(PROTO_DIR)

# ============================================================
# scaffold генерация шаблолна
# ============================================================
scaffold:
	PROJECT_NAME="$(PROJECT_NAME)" MODULE="$(MODULE)" \
		bash script/gen_stub.sh
	@if [ -x "$(GO_SCAFFOLD)" ]; then \
		PATH=$(BIN_DIR):$$PATH $(GO_SCAFFOLD) generate; \
	else \
		echo "go-scaffold not installed, skipping scaffold generation"; \
	fi

# ============================================================
# Lint
# ============================================================
lint:
	$(BUF_CMD) lint $(PROTO_DIR)

# ============================================================
# Go
# ============================================================
tidy:
	go mod tidy

run:
	go run ./cmd/$(PROJECT_NAME)

# ============================================================
# Clean
# ============================================================
clean:
	rm -rf $(GEN_DIR)
	rm -rf $(BIN_DIR)
	
# ============================================================
# Print-Vars
# ============================================================
print-vars:
	@echo "PROJECT_NAME = $(PROJECT_NAME)"
	@echo "MODULE       = $(MODULE)"

# ============================================================
# Buf
# ============================================================
BUF := ./bin/buf
PROTO_DIR := proto

.PHONY: buf-dep-update
buf-dep-update:
	$(BUF_CMD) dep update $(PROTO_DIR)

.PHONY: buf-lint
buf-lint:
	$(BUF) lint $(PROTO_DIR)