config:
    application_name:
        usage: Название приложения
        group: application
        value: "go-base"
        type: string
    server_grpc_port:
        usage: Порт который будет слушать GRPC сервер
        group: server
        value: ":50051"
        type: string
    server_http_port:
        usage: Порт который будет слушать HTTP (JSON API) сервер
        group: server
        value: ":8080"
        type: string
    server_swagger_port:
        usage: Порт который будет слушать Swagger сервер
        group: server
        value: ":8081"
        type: string
    server_metric_port:
        usage: Порт который будет слушать Prometheus сервер
        group: server
        value: ":2112"
        type: string
    server_swagger_host:
        usage: Хост на который будет ходить Swagger при try it out
        group: server
        value: "localhost:8080"
        type: string