// Code generated by generate_config.go; DO NOT EDIT.

package config

import (
	"context"
	"time"
)

type key string

func (k key) String() string {
	return string(k)
}

/*
ConfigProvider — интерфейс, который должен реализовать
твой runtime-конфиг (vault, consul, env и т.д.)
*/
type ConfigProvider interface {
	GetString(ctx context.Context, key string) string
	GetInt(ctx context.Context, key string) int
	GetBool(ctx context.Context, key string) bool
	GetDuration(ctx context.Context, key string) time.Duration
}

var provider ConfigProvider

// SetProvider должен вызываться при старте приложения
func SetProvider(p ConfigProvider) {
	provider = p
}

type Keys struct {
{{- range .Groups }}
{{- range .Items }}
	// {{ .Comment }}
	{{ .FieldName }} key
{{- end }}
{{- end }}
}

var K = Keys{
{{- range .Groups }}
{{- range .Items }}
	{{ .FieldName }}: "{{ .Key }}",
{{- end }}
{{- end }}
}

func GetString(ctx context.Context, k key) string {
	return provider.GetString(ctx, k.String())
}

func GetInt(ctx context.Context, k key) int {
	return provider.GetInt(ctx, k.String())
}

func GetBool(ctx context.Context, k key) bool {
	return provider.GetBool(ctx, k.String())
}

func GetDuration(ctx context.Context, k key) time.Duration {
	return provider.GetDuration(ctx, k.String())
}
