// Code generated by add_service.sh / make add-service. DO NOT EDIT MANUALLY.

syntax = "proto3";

package ${SERVICE_NAME_LOWER}.${PROTO_VERSION};

option go_package = "${MODULE}/gen/go/${SERVICE_NAME_LOWER}/${PROTO_VERSION};${SERVICE_NAME_LOWER}pb";

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";


// ${SERVICE_NAME_PASCAL}Service — основной сервис ${SERVICE_NAME_LOWER} (${PROTO_VERSION})
service ${SERVICE_NAME_PASCAL}Service {

  // GetStatus — простой health-check эндпоинт
  rpc GetStatus (GetStatusRequest) returns (GetStatusResponse) {
    option (google.api.http) = {
      get: "/${PROTO_VERSION}/${SERVICE_NAME_LOWER}/status"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary     : "Проверка статуса сервиса (${PROTO_VERSION})"
      description : "Возвращает статус, версию и текущее время"
      operation_id: "${SERVICE_NAME_LOWER}_${PROTO_VERSION}_get_status"
      tags        : "${SERVICE_NAME_LOWER}"
      responses   : {
        key   : "200"
        value : {
          description : "Успешный ответ"
        }
      }
    };
  }

  // Здесь будут добавляться остальные методы...
}

message GetStatusRequest {
  // Можно добавить поля, если нужно (например, для проверки конкретного компонента)
}

message GetStatusResponse {
  string status    = 1;  // "ok", "degraded", "down"
  string version   = 2;  // версия сервиса (api + app)
  string timestamp = 3;  // RFC3339
  // map<string, string> components = 4;  // опционально: статус подкомпонентов
}