// Code generated by generate_config.go; DO NOT EDIT.

package config

import (
	"context"
	"time"
)

type key string

func (k key) String() string {
	return string(k)
}

/*
ConfigProvider — интерфейс, который должен реализовать
твой runtime-конфиг (vault, consul, env и т.д.)
*/
type ConfigProvider interface {
	GetString(ctx context.Context, key string) string
	GetInt(ctx context.Context, key string) int
	GetBool(ctx context.Context, key string) bool
	GetDuration(ctx context.Context, key string) time.Duration
}

var provider ConfigProvider

// SetProvider должен вызываться при старте приложения
func SetProvider(p ConfigProvider) {
	provider = p
}

type Keys struct {
	// Название приложения
	ApplicationName key
	// Порт который будет слушать GRPC сервер
	ServerGrpcPort key
	// Порт который будет слушать HTTP (JSON API) сервер
	ServerHttpPort key
	// Порт который будет слушать Prometheus сервер
	ServerMetricPort key
	// Хост на который будет ходить Swagger при try it out
	ServerSwaggerHost key
	// Порт который будет слушать Swagger сервер
	ServerSwaggerPort key
}

var K = Keys{
	ApplicationName:   "application_name",
	ServerGrpcPort:    "server_grpc_port",
	ServerHttpPort:    "server_http_port",
	ServerMetricPort:  "server_metric_port",
	ServerSwaggerHost: "server_swagger_host",
	ServerSwaggerPort: "server_swagger_port",
}

func GetString(ctx context.Context, k key) string {
	return provider.GetString(ctx, k.String())
}

func GetInt(ctx context.Context, k key) int {
	return provider.GetInt(ctx, k.String())
}

func GetBool(ctx context.Context, k key) bool {
	return provider.GetBool(ctx, k.String())
}

func GetDuration(ctx context.Context, k key) time.Duration {
	return provider.GetDuration(ctx, k.String())
}
